repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.26.0  # Specify the desired version of Gitleaks
    hooks:
      - id: gitleaks
      
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.6.9'
    hooks:
      - id: ruff
        args: ['--fix']